# These are supported funding model platforms

# up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: # [IRONM00N]

# a single Patreon username
patreon: IRONM00N

# a single Open Collective username
open_collective:

#  a single Ko-fi username
ko_fi:

# a single Tidelift platform-name/package-name e.g., npm/babel
tidelift:

# a single Community Bridge project-name e.g., cloud-foundry
community_bridge:

# a single Liberapay username
liberapay:

# a single IssueHunt username
issuehunt:

# a single Otechie username
otechie:

# up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom:
